version: "2"

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - wrapcheck
    - tagalign
    - forbidigo
    - perfsprint
    - gochecknoglobals
    - wsl
    - revive
    - gochecknoinits
    - nlreturn
    - varnamelen
    - noctx
    - contextcheck
    - errcheck
    - gosec
    - canonicalheader
    - embeddedstructfieldcheck
    - wsl_v5
